amplitude/amplitude-docs

content/collections/destination-catalog/en/google-ads.md
Minor update to google ads to add `gclid` info
=> AMP-108054 Minor update to google ads

content/collections/retention-analysis/en/retention-analysis-build.md
=> Retention analysis article tweak

content/collections/experiment/en/web-experimentation.md
=> fix closing script tags in web exp doc

content/collections/account-management/en/self-service-data-deletion-in-amplitude.md, content/collections/data/en/remove-invalid-data.md, content/trees/collections/en/account-management.yaml, content/trees/navigation/en/admin.yaml
=> Self-serve data delete documentation

content/collections/warehouse_native_amplitude/en/warehouse-native-bulk-model-management.md, content/trees/collections/en/sections.yaml, content/trees/navigation/en/data.yaml
add doc for bulk model management in WNA
=> AMP-109095 add bulk model mangement doc

content/collections/analytics/en/product-analytics.md, content/collections/analytics/en/user-data-lookup.md, content/collections/analytics/en/web-analytics.md, content/collections/get-started/en/index.md, content/trees/collections/en/sections.yaml
=> October 15 fixes

content/collections/experiment-apis/en/experiment-management-api-experiments.md, content/collections/experiment-apis/en/experiment-management-api-flags.md
associated management api pr https://github.com/amplitude/javascript/pull/52073/files
=> SKY-6280 update schema for list experiment and list flag endpoint

.github/styles/config/vocabularies/dev/accept.txt, content/collections/cdp/en/audiences.md, content/collections/destination-catalog/en/appfit.md
=> today's tickets

content/collections/under-the-hood/en/event-tracking.md
Updating a note regarding the impact of exposure and assignment events on event volume. Per https://amplitude.slack.com/archives/C04LW12V65N/p1729877343740659
=> DOC-322 update event volume and billing note

content/collections/api/en/behavioral-cohorts.md
- Update the response for Upload cohort API.
=> Update the cohort upload response

content/collections/advanced-techniques/en/holdout-groups-exclude-users.md, content/collections/analytics/en/dashboard-preferences.md, content/collections/sections/en/session-replay.md, content/collections/session-replay/en/session-replay-google-tag-manager.md, resources/views/partials/session-replay/_sr-data-retention.antlers.html
DOC-307
DOC-311
DOC-320
DOC-323
=> Friday tickets

content/collections/web_experiment/en/implementation.md
https://github.com/user-attachments/assets/bd9168cc-769c-4aa0-8af0-527534de93ec
=> Fix broken link

vercel.json
- **fix some broken links w/ redirects**
- **fix instrument track sessions recursive redirect**
=> broken link fixes

content/collections/experiment/en/remote-evaluation.md, content/collections/web_experiment/en/implementation.md, public/docs/output/img/experiment/.meta/remote-evaluation.drawio.svg.yaml, public/docs/output/img/experiment/remote-evaluation.drawio.svg
Couple of changes I had staged but never committed:
* fix web experiment implementation headers
* Add remote eval diagram that was lost in migration
=> update web exp impl headings; add remote eval diagram

content/collections/source-catalog/en/snowflake.md
- Changing the naming for 'ingestion-only' to 'append-only' to align with UI
- Adding the 1B batch size limit to indicate that 1B size batch will be completed in 12 hours.
=> AMP-119500: updating snowflake docs

content/collections/api/en/taxonomy.md
Taxonomy API doc additions and updates for Delete and Restore ops for Events, Event Properties and User Properties.
=> AMP-114937 update taxonomy api docs to support new delete/restore functionality

resources/views/partials/session-replay/_sr-android-known-limitations.antlers.html
Adding note clarifying that jetpack compose isn't supported
=> fix: update android SR docs to clarify jetpack compose isn't supported

content/collections/api/en/user-privacy.md
Updating the limits to describe concurrent cost as well
See: https://amplitude.atlassian.net/browse/AMP-121051
=> Update user-privacy.md to include information about concurrent cost

content/collections/session-replay/en/session-replay-android-middleware.md, content/collections/session-replay/en/session-replay-android-plugin.md, content/collections/session-replay/en/session-replay-android-standalone.md, content/collections/session-replay/en/session-replay-ios-middleware.md, content/collections/session-replay/en/session-replay-ios-plugin.md, content/collections/session-replay/en/session-replay-ios-segment-integration.md, content/collections/session-replay/en/session-replay-ios-standalone-sdk.md, resources/views/partials/session-replay/_sr-android-known-limitations.antlers.html, resources/views/partials/session-replay/_sr-android-mask-data.antlers.html, resources/views/partials/session-replay/_sr-android-webview-mapview.antlers.html, resources/views/partials/session-replay/_sr-ios-known-limitations.antlers.html, resources/views/partials/session-replay/_sr-ios-mask-data.antlers.html, resources/views/partials/session-replay/_sr-ios-webview.antlers.html
Adding support for web views and map views in session replay
=> chore: adding instructions for webview and map views

content/collections/experiment-apis/en/experiment-evaluation-api.md, content/collections/experiment/en/data-model.md
=> Add link to more info for experiment evaluation context

content/collections/browser_sdk/en/browser-sdk-2.md
https://amplitude.atlassian.net/browse/DOC-424
=> revised autocapture remote explanation

content/collections/account-management/en/self-service-data-deletion-in-amplitude.md, content/collections/faq_and_troubleshooting/en/modify-or-delete-historical-data.md
- **DOC-422 update plan-type limits**
- **DOC-421 historical data faq update**
=> deletion updates

content/collections/flutter_sdk/en/flutter-sdk-4-0-migration-guide.md
Extension of #456; needed to request review from SDK team and address comments.
=> Add docs for Flutter Web on Flutter 4.0

content/collections/analytics/en/out-of-the-box-metrics.md, content/collections/data-tables/en/data-tables-create-metric.md, content/trees/collections/en/analytics.yaml, content/trees/navigation/en/analytics.yaml
- **DOC-423 cleanup create a metric**
- **DOC-423 init**
- **DOC-423 draft**
- **DOC-423 add to nav**
- **DOC-423 add to nav**
[Preview](https://amplitude-docs-git-doc-423-amplitude-inc.vercel.app/docs/analytics/out-of-the-box-metrics)
=> DOC 423 OOTB Metrics

content/collections/analytics/en/out-of-the-box-metrics.md, content/collections/api/en/dashboard-rest.md, content/collections/api/en/user-profile.md, content/collections/audiences/en/recommendations-use.md, content/collections/charts/en/customize-your-charts-colors.md, content/collections/data/en/data-access-control.md, content/collections/data/en/streaming-transformations.md, content/collections/data/en/sync-cohorts-with-destinations.md, content/collections/destination-catalog/en/braze.md, content/collections/destination-catalog/en/customer-io.md, content/collections/destination-catalog/en/google-ads-cohort-syncing.md, content/collections/destination-catalog/en/google-analytics-4-ios-android.md, content/collections/destination-catalog/en/google-analytics-4-web.md, content/collections/destination-catalog/en/intercom.md, content/collections/destination-catalog/en/iterable.md, content/collections/destination-catalog/en/meta-pixel.md, content/collections/destination-catalog/en/snowflake-data-share.md, content/collections/session-replay/en/session-replay-standalone-sdk.md, content/collections/source-catalog/en/databricks.md, content/collections/source-catalog/en/snowflake.md, content/collections/web_experiment/en/performance.md, content/collections/web_experiment/en/set-up-a-web-experiment.md, content/collections/workflow/en/experiment-troubleshoot.md
- **DOC-408 web exp ad blocking notes**
- **DOC-408 fix typo**
- **DOC-444 update chart colors availability**
- **DOC-443 user profile api security note**
- **DOC-442 google ads, not google ads manager**
- **DOC-441 updates to DAC**
- **DOC-440 update info about cohort sync timing**
- **DOC-438 add detail to troubleshoot SR/Segment implementation**
- **DOC-437 Dashboard REST API clarification**
- **DOC-436 add note about available metric**
- **DOC-434 fix code sample formatting**
- **DOC-433 snowflake clarification**
- **DOC-432 CDC limitations**
- **DOC-431 CDP -> Activation**
=> Weekly fixes and jiras

content/collections/data-tables/en/entry-exit-analysis.md, content/trees/collections/en/data-tables.yaml, content/trees/navigation/en/charts.yaml
Preview: https://amplitude-docs-git-doc-452-amplitude-inc.vercel.app/docs/analytics/charts/data-tables/entry-exit-analysis
=> DOC-452 Entry / Exit analysis

content/collections/advanced-techniques/en/server-side-rendering.md, content/collections/analytics/en/breadcrumbs.md, content/collections/api/en/lookup-table-2.md, content/collections/funnel-analysis/en/funnel-analysis-build.md, content/collections/funnel-analysis/en/funnel-analysis-hold-properties-constant.md, content/collections/guides_and_surveys/en/get-started.md, content/collections/workflow/en/experiment-learnings.md
- **DOC-445**
- **DOC-446**
- **DOC-448**
- **DOC-449**
- **DOC-460**
- **DOC-451**
- **DOC-453**
=> 20250214 fixes

content/collections/experiment/en/implementation.md
Just adding an explanation about bucketing salt and when to change it since we sometimes get this question
=> Add explanation about bucketing salt

content/collections/data/en/display-names-in-amplitude-data.md, content/collections/data/en/visual-labeling.md
- **DOC-456 event visibility**
- **DOC-458 Labeled event break detection**
Previews:
- [Event Visibility](https://amplitude-docs-git-dataupdates-amplitude-inc.vercel.app/docs/data/display-names-in-amplitude-data#update-an-events-visibility)
- [Break detection](https://amplitude-docs-git-dataupdates-amplitude-inc.vercel.app/docs/data/visual-labeling#find-misconfigured-events)
=> Data release updates

content/collections/destination-catalog/en/marketo-static-list.md
Due to recent changes to the integration, updating the docs to reflect this.
=> AMP-125323: Update marketo-static-list.md

content/collections/account-management/en/user-roles-permissions.md, content/collections/guides_and_surveys/en/experiments.md, content/collections/guides_and_surveys/en/get-started.md, content/collections/guides_and_surveys/en/guides-and-surveys-user-permissions.md, content/trees/collections/en/guides_and_surveys.yaml, content/trees/navigation/en/guides_and_surveys.yaml
- **DOC-491 init**
- **DOC-491 add more detail**
=> DOC-391 G&S roles and permissions

.gitignore, content/collections/source-catalog/en/databricks.md, content/collections/source-catalog/en/snowflake.md
Update Snowflake and Databricks setup instructions to reflect tweaks to mutation setup process;
=> Update Snowflake and Databricks setup instructions

content/collections/session-replay/en/session-replay-android-plugin.md, content/collections/session-replay/en/session-replay-android-standalone.md, content/collections/session-replay/en/session-replay-ios-middleware.md, content/collections/session-replay/en/session-replay-ios-plugin.md, content/collections/session-replay/en/session-replay-ios-segment-integration.md, content/collections/session-replay/en/session-replay-ios-standalone-sdk.md, content/collections/session-replay/en/session-replay-react-native-sdk-plugin.md, content/collections/session-replay/en/session-replay-rudderstack-integration.md, content/globals/en/sdk_versions.yaml, content/trees/collections/en/session-replay.yaml, content/trees/navigation/en/session_replay.yaml, resources/blueprints/collections/session-replay/session-replay.yaml, resources/views/partials/session-replay/_sr-instrumentation-landing.antlers.html
Preview: https://amplitude-docs-git-doc-566-amplitude-inc.vercel.app/docs/session-replay/session-replay-react-native-sdk-plugin
=> DOC-566 Session Replay RN SDK draft

content/collections/analytics/en/out-of-the-box-metrics.md, content/collections/analytics/en/web-analytics.md
ticket: https://amplitude.atlassian.net/browse/AMP-125382
- rename web analytics to marketing analytics
- add the "Ads" bullet based on content of https://amplitude.slack.com/archives/C0FP9AD7W/p1740686297114849
Won't merge this until we release Ads in beta.
I wasn't sure if I should open a PR, or a ticket, but I figured a PR would be faster. Let me know if this is cool!
=> Amp 125382 marketing analytics docs

content/collections/analytics/en/web-analytics.md
remove `open beta` note bc we are GA'ing
=> feat: remove open beta tag

content/collections/analytics/en/web-analytics.md
https://amplitude.slack.com/archives/C08HJC9298C/p1743458821057849
=> feat: add more details

resources/views/partials/_rating.antlers.html
- **DOC-592 Add Survey for doc Rating**
- **DOC-592 star highlighting was confusing**
=> DOC-592 Migrate doc rating to Survey

content/collections/analytics/en/web-analytics.md
https://amplitude.slack.com/archives/C06HVKCK997/p1743457236912949
=> feat: update missing web to marketing

content/collections/source-catalog/en/databricks.md
add troubleshooting doc for databricks import
=> AMP-127752 add troubleshooting doc for databricks import

content/collections/session-replay/en/session-replay-plugin.md, content/collections/session-replay/en/session-replay-standalone-sdk.md, resources/views/partials/session-replay/_sr-web-storage.antlers.html
@markzegarelli feel free to make edits as needed!
=> SR-822 [session-replay] update session replay storage section

content/collections/under-the-hood/en/event-tracking.md
Update experiment user property limit from 700 to 1500.
=> Update experiment user property limit

content/collections/data/en/streaming-transformations.md
- **Add note that computations aren't avaiable in EU**
- **DOC-585 G&S Share link**
- **DOC-587 add limitation about streaming transformations**
=> DOC-587 streaming transformation limitation

content/globals/en/sdk_versions.yaml
Bumping the version of SR SDKs.
=> Version bump session replay plugin and standalone

content/collections/data/en/csv-import-export.md
We've added support for new columns in the CSV Import/Export API in Data, specifically
1. Event Hidden From Dropdowns
2. Event Hidden From Persona Results
3. Event Hidden From Pathfinder
4. Event Hidden From Timeline
5. Property Visibility (For both event and user properties)
Also added a missing column - Object Owner
=> AMP-128168 [data] update csv import/export docs

content/collections/get-started/en/autocapture.md, content/collections/ios_sdk/en/ios-swift-sdk.md
=> AMP-125615 [Doc] add doc for network tracking

content/collections/data/en/change-event-category.md, content/collections/data/en/visual-labeling.md
=> AMP-125421 modify Event Categorization and Visual Labeler pages to include categories for custom/labeled events

content/collections/session-replay/en/session-replay-react-native-sdk-plugin.md
Add doc for logLevel and start/stop replay
=> AMP-126835: update Session Replay React Native doc

content/collections/guides_and_surveys/en/sdk.md
These were previously incorrectly documented as snake case. They should be camel case!
=> fix: update setThemeMode's mode options to camelCase

content/collections/apis/en/guides-and-surveys.md, content/collections/guides-and-surveys-apis/en/guides-and-surveys-api-localization.md, content/collections/guides_and_surveys_api.yaml, content/collections/guides_and_surveys_api/en/guides-and-surveys-api-localization.md, content/collections/sections/en/apis.md, content/navigation/apis.yaml, content/trees/navigation/en/apis.yaml
Mimics the Experiment API doc structure
=> Add basic localization API docs

content/collections/guides_and_surveys/en/sdk.md
We have a new SDK method to update language mid-session.
=> Guides and Surveys: Document new updateLanguage SDK method

content/collections/guides_and_surveys/en/proxy.md
related slack thread: https://amplitude.slack.com/archives/C0884U79ZDW/p1747231248886959
=> clarify cdn.eu.amplitude on proxy doc

content/collections/android_sdk/en/android-kotlin-sdk.md
As part of https://github.com/amplitude/Amplitude-Kotlin/pull/300.
I'll merge this when we're about to release the next version.
=> add min sdk requirement for android

content/collections/guides_and_surveys/en/localization.md
https://amplitude.slack.com/archives/C07SDD9ECL9/p1750801976502879
=> Make it clear that using xliff is optional for guides and surveys localization

content/collections/guides_and_surveys/en/resource-center-autopilot.md, content/collections/guides_and_surveys/en/resource-center-recommendation-sets.md, content/collections/guides_and_surveys/en/resource-center-settings.md, content/collections/guides_and_surveys/en/resource-center-source-content.md, content/collections/guides_and_surveys/en/resource-center-targeting-recommendation-sets.md, content/collections/guides_and_surveys/en/resource-center-website-scraper.md
Add tabs for Website scraper, style changes for task headings
=> Style changes

content/collections/account-management/en/manage-permission-groups.md, content/collections/account-management/en/user-roles-permissions.md, content/collections/session-replay/en/heatmaps.md
Users with View permissions can create Heatmaps
=> Update Heatmaps permissions info

content/collections/destination-catalog/en/moloco.md
This updates the Moloco's doc on the `Moloco Commerce Media (MCM)` integration.
- MCM Link: https://www.moloco.com/solutions/moloco-commerce-media
- Contact Point: https://www.moloco.com/contact-us
=> Update moloco.md with MCM link and Contact point.

content/collections/guides_and_surveys/en/setup-and-target.md
=> bucketing and rollout percentage for G&S

content/collections/destination-catalog/en/cohort-webhooks.md
https://amplitude.atlassian.net/browse/AMP-129495
Preview testing:
=> AMP-129495: Change cohort webhook doc

content/collections/guides_and_surveys/en/templates.md, content/trees/navigation/en/guides_and_surveys.yaml
Added a draft for admin-created templates. 
Needs an id and added to the sidenav before publishing
=> add unpublished 'admin-created templates page

content/collections/guides_and_surveys/en/sdk.md, content/collections/guides_and_surveys/en/setup-and-target.md
Documenting our new session properties feature that's behind a feature flag
- updated the SDK ([screenshot](https://share.amplitude.com/1bdhzsHY))
- updated our targeting section ([screenshot](https://share.amplitude.com/NvQXpqpb))
Cleanup edits unrelated to session properties
- make "limits" an h2
- mention localization in setup and targeting doc
=> new: session properties

content/collections/source-catalog/en/hubspot-quickstart.md
Video of setup: https://amplitude.zoom.us/clips/share/BrFSasPxTdm3A-oW7SlKtQ
=> AMP-133545: Update HubSpot quickstart documentation

app/Console/Commands/DebugBundleCache.php, app/Tags/BundlePhobia.php, build.sh, config/app.php, public/docs/css/site.css, resources/views/partials/_bundle-size.antlers.html, routes/api.php
- **DOC-843 add fallback for bundlephobia**
- **DOC-843 fix API call**
- **DOC-843 remove fallback data**
- **DOC-843 cache improvements**
=> DOC-843 better bundle size fallback

content/collections/partners/en/create-a-cohort-sync-integration.md, content/collections/partners/en/create-a-cohort-syncing-integration.md, content/collections/partners/en/create-an-event-ingestion-integration.md, content/collections/partners/en/create-an-event-streaming-integration.md, content/collections/partners/en/integration-portal.md
Updating docs for GA release of Integration portal
=> Integration portal GA

content/collections/web_experiment/en/implementation.md, content/collections/web_experiment/en/set-up-a-web-experiment.md
Reverts amplitude/amplitude-docs#944
=> Revert "docs: Document preview mode persistence for multi-page applications"

content/collections/guides_and_surveys/en/guides-and-surveys-rn-sdk.md
The only requirement right now is that they use the new RN architecture
[Screenshot](https://share.amplitude.com/zGZyRwlv)
=> add RN requirements

content/collections/browser_sdk/en/browser-sdk-2.md, content/collections/get-started/en/autocapture.md
=> document networkTracking request and response headers/body

content/collections/guides_and_surveys/en/form-factors.md
Add "Submit app store rating request" table entry and accompanying Note
=> GSDK-464: update docs for iOS G&S app store review action

content/collections/guides_and_surveys/en/survey-overview.md
Adds the new survey templates types. 
- **[Preview link](https://amplitude-docs-git-add-new-survey-templates-amplitude-inc.vercel.app/docs/guides-and-surveys/surveys/survey-overview)** 
- [In-product ref here. ](https://share.amplitude.com/7ygQn0TW)
=> Add new survey templates

content/collections/guides_and_surveys/en/guides-and-surveys-android-sdk.md, content/collections/guides_and_surveys/en/guides-and-surveys-ios-sdk.md
Web for reference: https://amplitude.com/docs/guides-and-surveys/sdk#router-configuration
=> GSDK-561 Add docs for Android router configuration

content/collections/session-replay/en/session-replay-ios-middleware.md, content/collections/session-replay/en/session-replay-ios-plugin.md, content/collections/session-replay/en/session-replay-ios-segment-integration.md, content/collections/session-replay/en/session-replay-ios-standalone-sdk.md, resources/views/partials/session-replay/_sr-ios-config.antlers.html, resources/views/partials/session-replay/_sr-ios-log-recording.antlers.html
Add the log record feature description to the iOS Session Replay SDK docs
=> [docs] add ios sdk log record

content/collections/api/en/http-v2.md, content/collections/data/en/derived-properties.md
=> 20250924 sw

content/collections/api/en/http-v2.md, content/collections/faq_and_troubleshooting/en/data-tables.md
=> 20250925 sw

content/collections/guides_and_surveys/en/guides-and-surveys-rn-sdk.md
Clarify the process of booting the plugin for Guides and Surveys.
=> Update booting instructions for the plugin
