amplitude/amplitude-docs

- content/collections/analytics/en/behavior-offset.md
- content/collections/analytics/en/collaborate-with-spaces.md
- content/collections/experiment-results/en/experiment-results-use-formula-metrics.md
- content/collections/partners/en/integration-portal.md
- content/collections/web_experiment/en/actions.md
- content/collections/web_experiment/en/implementation.md
- content/collections/web_experiment/en/performance.md
- content/collections/web_experiment/en/set-up-a-web-experiment.md
- content/collections/web_experiment/en/targeting.md
- content/collections/web_experiment/en/tracking.md
- content/collections/workflow/en/multi-armed-bandit-experiments.md
DOC-262
DOC-220
DOC-293
DOC-288
DOC-276
DOC-292
> various tickets

- content/collections/data/en/amplitude-data-settings.md
This adds a section in _Manage your Amplitude Data settings_ about the new Permissions Tab and its functionality.
> AMP-109903 Update docs for data permission restrictions

- content/collections/api/en/taxonomy.md
1. Add `overrideScope` and `classifications` wherever necessary for DAC GA.
2. Document new Group Properties API.
> AMP-111643 Update Taxonomy API docs

- content/collections/experiment-sdks/en/experiment-go.md
- content/collections/experiment-sdks/en/experiment-jvm.md
- content/collections/experiment-sdks/en/experiment-node-js.md
- content/collections/experiment-sdks/en/experiment-python.md
- content/collections/experiment-sdks/en/experiment-ruby.md
Fix issue due to extra newline in description:
> fix Experiment cohort sync config table

- content/collections/experiment-sdks/en/experiment-go.md
The Go SDK part of stream flags. Same language as JVM SDK.
> Add stream flag doc for Go SDK

- content/collections/browser_sdk/en/migrate-from-javascript-sdk-to-browser-sdk-2-0.md
JIRA: [AMP-118022]
Currently, we only have migration guides
- from JS SDK to Browser TS 1.x
- from Browser TS 1.x to Browser TS 2.x
This PR adds the one from JS SDK to Browser TS 2.x. 
[AMP-118022]: https://amplitude.atlassian.net/browse/AMP-118022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add browser SDK migration guide from JS to TS 2.x

- content/collections/source-catalog/en/snowflake.md
@chrisseldo Here are the updates you requested to Snowflake Data ImportL
https://amplitude-docs-git-doc-324-amplitude-inc.vercel.app/docs/data/source-catalog/snowflake#sql-troubleshooting
> DOC-324 Add more SQL to Snowflake import doc

- content/collections/experiment-sdks/en/experiment-jvm.md
> Updated Experiment JVM doc

- content/collections/browser_sdk/en/browser-sdk-1.md
- content/collections/browser_sdk/en/browser-sdk-2.md
Source: https://discourse.amplitude.com/t/browser-sdk-2-0-init-callback-possibility/11035/10
`init()` returns `Promise<void>`.
> fix: browser sdk init callback should accept no param

- content/collections/source-catalog/en/google-tag-manager.md
Source: https://discourse.amplitude.com/t/what-is-the-correct-value-to-send-to-set-amplitude-via-gtm-to-leverage-navigator-sendbeacon/15034/3
Fix the words of setting sendBeacon on GTM template.
> fix: gtm sendbeacon

- content/collections/warehouse_native_amplitude/en/warehouse-native-bulk-model-management.md
We've removed `isActive` field from **bulk model management**, as show in the PR here
https://github.com/amplitude/nova/commit/d029960aba383244ad71f37978166ee0cd064ff7
We'll need to update our documentation accordingly. I removed `isActive` references that is found throughout the docs. Not much risk here. 
https://github.com/user-attachments/assets/dbbe0816-671b-48ca-ae50-2d4c7b336a56
We'll need to verify the push through pipeline and then verify that there aren't any weird docs issues when it touches prod. Even with the above template, it's not truly 1:1. 
Maybe there's a way to 100% test docs locally? I'll need to sync with @xiaowuc1 on this. 
EDIT: Additionally, do we have to coordinate the push to prod with anyone? Or let people know that docs are changing?
Or is this just something …
> [AMP-119883] Removed References to isActive in WNA Docs

- content/collections/browser_sdk/en/browser-sdk-2.md
[AMP-118975]
There is one customer using sendBeacon() (type is ping on the network tab) and gets wrong event orders received by the server which result in some session start events missing UTMs. We should NOT encourage customers to set sendBeacon on initialization to avoid missing UTMs. This PR calls out this caveat. 
[AMP-118975]: https://amplitude.atlassian.net/browse/AMP-118975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AMP-118975 sendBeacon() warning

- content/collections/flutter_sdk/en/flutter-sdk-4-0-migration-guide.md
- content/collections/flutter_sdk/en/flutter-sdk-4-0.md
- Added new configuration options for Flutter Web
- Added snippet to use for setting up Flutter projects with Amplitude Browser SDK in web/index.html
> Add docs for Flutter Web on Flutter 4.0

- content/collections/destination-catalog/en/amazon-redshift.md
We're adding some more info to Redshift docs in order for customer to be more aware of potential errors that could come from export. We've init the running list, and now we've added an error we've gotten recently 
https://amplitude.atlassian.net/browse/AMP-120354
We'll need to verify the push through pipeline and then verify that there aren't any weird docs issues when it touches prod. Even with the above template, it's not truly 1:1.
> [AMP-121855] Quick Improvement to Redshift Docs for String Errors

- content/collections/flutter_sdk/en/flutter-sdk-4-0.md
- bumped minimum version to support macOS
- Added instructions for adding minimum osx version to macOS podfile
- Added instructions for adding entitlements to macOS folder of flutter project to enable network requests
> Add instructions for macOS installation for flutter SDK

- content/collections/web_experiment/en/targeting.md
We made a decision to update some naming in-product for web experiment targeting to remove language around local/remote evaluation for the web exp persona so only the docs will contain the details around evaluation.
Local property targeting -> Browser property targeting
Remote property targeting -> User property targeting
There are no changes for feature experiment.
This is the update to the in-product segment control:
docs update:
> Rename web experiment properties

- content/collections/analytics/en/share-external.md
Zach Stuart added support for public links on persona chart types some time ago, so this comment is no longer necessary.
> Remove outdated comment about persona charts

- content/collections/flutter_sdk/en/flutter-sdk-4-0.md
- content/collections/flutter_sdk/en/flutter-sdk.md
Our docs do not include a compatibility for Flutter, though our Github repo READMEs do. Our React Native docs have the compatibility matrix, so adding here for consistency and convenience for users.
> Add compatibility matrix for flutter docs for 3.x and 4.x

- content/collections/analytics/en/microscope.md
- content/collections/analytics/en/session-replay.md
- content/collections/analytics/en/user-data-lookup.md
- content/collections/sections/en/session-replay.md
This PR updates 3 places in our public docs (microscope, user-data-lookup and session-replay) adding a note mentioning that they might see Autocapture Suggested Event Names in these event streams.
Note being added
> Event names with a *sparkle* icon indicate that we've generated a name to provide more context around the action a user is taking. These are Autocapture events ingested as `Page Viewed`, `Element Clicked`, and `Element Changed`, but we're using property information to make them more valuable in the event stream. You can click on any of them to see their ingested name and properties.
> AMP-122299 autocapture suggested event name updates

- content/collections/api/en/taxonomy.md
1. Events - Support ability to set `is_active`, `is_hidden_from_dropdowns`, `is_hidden_from_persona_results`, `is_hidden_from_pathfinder`, `is_hidden_from_timeline`, `tags` and `owner` for events.
2. Properties - Support ability to set `is_hidden` status for properties.
> AMP-124739 [taxonomy-api] add ability to set activity, hidden status, tags and owner for events and/or properties

- content/collections/destination-catalog/en/amazon-s3-cohort.md
- We want to add a “Note” under the Setup section for S3 Cohort, similar to Marketo. [Marketo Static List](https://amplitude.com/docs/data/destination-catalog/marketo-static-list)
> Update S3 Cohort doc to note about the change to IAM role-based access

- content/collections/flutter_sdk/en/flutter-sdk-4.md
Previously instructions directed users to install a minimum version that was a beta (`^4.0.0-beta.7`). Rather than specifying a specific version, direct users to use the method that `pub.dev` recommends (`flutter pub add amplitude_flutter`) which will never be out of date.
> Flutter SDK docs update install instructions

- content/collections/charts/en/build-charts-add-events.md
- content/collections/data/en/create-tracking-plan.md
- content/collections/data/en/object-management.md
- content/collections/user-sessions/en/user-sessions-track-engagement-frequency.md
- **DOC-483 update language around 'tracking plan'**
- **DOC-480**
- **DOC-469**
- **DOC-475**
> 20250307 fixes

- content/collections/guides_and_surveys/en/sdk.md
Add instructions for using Segment with the NPM package. This was an edge case we hadn't covered in the original docs, and is tricky because it requires calling `init`. Normally the `init` call isn't needed, because it's done via the dynamic script, but when installing via NPM it's required.
I tested these instructions locally and they worked well for me. Instructions are a bit rough around the edges, but there's a customer who's actively planning on using this setup, so I'd like to get these out sooner rather than later.
Import the Guides and Surveys package
```bash
yarn add @amplitude/engagement-browser
```
Connect Guides and Surveys with Segment:
```ts
import { init as engagementInit } from '@amplitude/engagement-browser';
// This was the piece that was missing before …
```
> Using the G&S NPM package with 3rd party analytics

- content/collections/guides_and_surveys/en/build-a-survey.md
- content/collections/guides_and_surveys/en/survey-overview.md
JIRA Task: https://amplitude.atlassian.net/browse/FOO-1355
Changes: 
- Update Survey → Overview → Survey templates -> `guide` link
Preview link: https://amplitude-docs-git-ninooooonin-foo-1355-fi-c652c0-amplitude-inc.vercel.app/docs/guides-and-surveys/surveys/survey-overview#survey-templates
- Update Surveys → Build a survey → Setup and target your survey -> `guides` link
Preview link:
https://amplitude-docs-git-ninooooonin-foo-1355-fi-c652c0-amplitude-inc.vercel.app/docs/guides-and-surveys/surveys/build-a-survey#setup-and-target-your-survey
> [Guides and Surveys] Update incorrect docs links

- content/collections/api/en/dashboard-rest.md
It doesn't make sense that we ask people to use /query as the response format makes more sense for our charts better for them to just call /csv instead. It is confusing to end customers https://amplitude.slack.com/archives/C02RN1UPBNY/p1741704106052699 and https://community.amplitude.com/building-and-sharing-your-analysis-58/chart-api-does-not-return-series-labels-1272 and https://community.amplitude.com/ideas/add-column-headers-to-chart-api-response-4317
> AMP-126286 Update docs to /csv instead of /query

- content/collections/guides_and_surveys/en/sdk.md
Make documentation around `boot` and `init` more explicit and tweak descriptions for a couple SDK methods.
> Clarify install instructions

- content/collections/instrumentation/en/sdk-quickstart.md
- content/collections/ios_sdk/en/ampli-for-ios-swift-sdk.md
- content/collections/ios_sdk/en/ios-swift-sdk.md
- content/globals/en/sdk_versions.yaml
- `flushMaxRetries` was not actually used in previous versions of Amplitude-Swift. Version 1.11.9 fixed this issue and changed the default value from `5` to `6`.
- Change installation suggestion to `~> 1.0`. The old suggestion only matches versions at 1.0.x.
> chore: update doc for Amplitude-Swift

- content/collections/ios_sdk/en/ios-swift-sdk.md
Adding `maxQueuedEventCount` config property
> chore: add max queued event count to iOS config

- content/collections/api/en/ccpa-dsar.md
The doc is confusing right now because `-u` and encoded header are mix used. And the encoded header isn't even valid.
After this change, all curl commands use the `-u` open and all scripts use the encoded string.
Also, userId is a string, not a number in the examples.
> AMP-129465 [doc] Update DSAR document

- content/collections/ios_sdk/en/ios-swift-sdk.md
Add the `autocapture = .all` option to the example code
> AMP-125615: add autocapture option to example code

- content/collections/android_sdk/en/android-kotlin-sdk.md
- content/collections/android_sdk/en/android-sdk.md
We're now defaulting location tracking to false for Android to address the privacy issue flagged by Google (see [JIRA ticket](https://amplitude.atlassian.net/browse/AMP-127891)).
This update is for making sure that clients are informed of this behavior change if they still want to opt-in to the previous behavior.
- Legacy - https://github.com/amplitude/Amplitude-Android/releases/tag/v2.40.3
- Kotlin - https://github.com/amplitude/Amplitude-Kotlin/releases/tag/v1.20.7
> update Android SDKs to reflect the recent changes for location tracking

- content/collections/guides_and_surveys/en/localization.md
Adds an admonition w/ info about which parts of the xliff should be edited to add translations:
> Add example of updating an xliff translation file

- content/collections/browser_sdk/en/browser-unified-sdk.md
Set sample rate to 1 in the example to help customers enable session replay.
> AMP-131331 update web unified SDK 

- content/collections/web_experiment/en/implementation.md
Update web exp implementation docs with Cross-Origin-Opener-Policy requirements for initializing visual editor.
> Update web exp implementation docs with COOP reqs

- content/collections/funnel-analysis/en/funnel-analysis-how-amplitude-computes-conversions.md
- content/collections/source-catalog/en/snowflake.md
More details from this discourse question: https://discourse.amplitude.com/t/snowflake-import-retry-mechanism-clarifications/16398
> DOC-581 [SnowflakeImport] Adding a FAQ session to Snowflake Import doc

- content/collections/api/en/scim.md
A customer was having trouble setting up the SCIM API, and I found it was because we were directing them to use an incorrect base URL given they are in the EU data center.
| Before | After |
| --- | --- |
| ![Screenshot 2025-06-04 at 3 12 57 PM](https://github.com/user-attachments/assets/093a0559-8d49-479f-bdec-a54890bfcf53) | ![Screenshot 2025-06-04 at 3 12 36 PM](https://github.com/user-attachments/assets/f1c4e9d4-9579-484d-b438-8f0ccbf24bcb) |
[AMP-63816]: https://amplitude.atlassian.net/browse/AMP-63816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AMP-63816 Add EU endpoint to SCIM docs

- content/collections/source-catalog/en/snowflake.md
This PR updates the developer documentation for Snowflake import to reflect the recent change in how we handle ABORT_DETACHED_QUERY.
* Clarified that ABORT_DETACHED_QUERY = FALSE is now automatically set at the session level during import.
* Removed outdated instructions suggesting customers set this manually at the account level.
> AMP-132981 [SnowflakeImport] Update developer docs to reflect ABORT_DETACHED_QUERY session-level behavior

- content/collections/browser_sdk/en/browser-sdk-2.md
Angular (particularly it's ZoneJS library) doesn't play nicely with our Browser SDK. This update gives users a warning about Angular and instructs them how to avoid this problem.
> warn browser SDK users about angular

- content/collections/guides_and_surveys/en/build-a-survey.md
- content/collections/guides_and_surveys/en/form-factors.md
- content/collections/guides_and_surveys/en/guide-overview.md
Split out web tag changes from carousel PR: https://github.com/amplitude/amplitude-docs/pull/932
> Remove "web only" for randomize order, other option, and text animation

- content/collections/get-started/en/autocapture.md
Take elementInteractions out of defaults from autocapture snippets
> remove elementInteraction from autocapture snippet

- content/collections/guides_and_surveys/en/guides-and-surveys-rn-sdk.md
- "new" RN architecture
- note: the `"new"` copy was removed before by @JeffScattini-amplitude. I think it's important to note that we only support the "new" RN architecture (not the "old" RN architecture)
- some RN specifics
- some iOS specifics
> update RN SDK requirements

- content/collections/experiment/en/managing-flags-and-experiments-with-approvals.md
- content/trees/collections/en/experiment.yaml
- content/trees/navigation/en/experiment.yaml
- public/mix-manifest.json
The new Experiment Approvals feature is going live in the next week and this is intended to be a basic guide for using approvals. 
Please let me know if there are any questions about the feature!
> Add draft for experiment approvals

- content/collections/guides_and_surveys/en/proxy.md
- content/collections/guides_and_surveys/en/sdk.md
This change documents the new mediaUrl initialization parameter that enables proxying of guides and surveys images.
Previously, customers using proxy setups would encounter broken images in guides because images were still loading directly from engagement-static.amplitude.com, which could be blocked by corporate firewalls or content security policies.
> FOO-1942 add documentation on proxying images with mediaUrl
